[package]
name = "euphony-osc-macros"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.12"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
