[package]
name = "euphony-graph"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
slotmap = { version = "1", default-features = false }
rayon = { version = "1", optional = true }

[dev-dependencies]
bolero = "0.6"
rayon = "1"
