[package]
name = "example-scale"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
euphony = { version = "0.1", path = "../euphony" }

[build-dependencies]
euphony-build = { version = "0.1", path = "../euphony-build" }
