[package]
name = "euphony-mix"
version = "0.1.1"
description = "mixing logic for euphony compositions"
edition = "2021"
license = "MIT"

[dependencies]
dasp_frame = "0.11"
euphony-dsp = { version = "0.1", path = "../euphony-dsp" }
euphony-units = { version = "0.1", path = "../euphony-units" }
