[package]
name = "euphony-cli"
description = "Command line tool for managing euphony projects"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1"
cargo_metadata = "0.14"
futures = "0.3"
notify = "4"
serde_json = "1"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
warp = { version = "0.3", default-features = false }
