[package]
name = "euphony-buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
blake3 = "1"
euphony-command = { version = "0.1", path = "../euphony-command" }
once_cell = "1"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
symphonia = "0.5"
tempfile = "3"