[package]
name = "euphony-command"
description = "command descriptions for euphony applications"
version = "0.1.1"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
bach = "0.0.6"

[dev-dependencies]
bolero = "0.7"
