[package]
name = "euphony-command"
version = "0.1.0"
edition = "2021"

[dependencies]
euphony-core-macros = { version = "0.1", path = "../euphony-core-macros" }
euphony-dsp = { version = "0.1", path = "../euphony-dsp" }
fastapprox = "0.3"
serde = { version = "1", features = ["derive"] }
